import React from 'react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { cleanup, render, screen } from '@testing-library/react';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { compile, run } from '@mdx-js/mdx';
import * as jsxRuntime from 'react/jsx-runtime';
import matter from '@11ty/gray-matter';

const require = createRequire(import.meta.url);
const { DefaultSidebarItemsGenerator } = require('@docusaurus/plugin-content-docs/lib/sidebars/generator.js');
const { postProcessSidebars } = require('@docusaurus/plugin-content-docs/lib/sidebars/postProcessor.js');
const root = new URL('../../', import.meta.url);

afterEach(cleanup);

const locales = [
  {
    locale: 'en',
    directory: 'gaming',
    titles: ['Gaming Notes', 'Game Development'],
    emptyStates: [
      'No gaming notes have been published yet.',
      'No game development entries have been published yet.',
    ],
  },
  {
    locale: 'es',
    directory: 'i18n/es/docusaurus-plugin-content-docs-gaming/current',
    titles: ['Notas de Gaming', 'Desarrollo de Videojuegos'],
    emptyStates: [
      'Aún no se han publicado notas de gaming.',
      'Aún no se han publicado artículos de desarrollo de videojuegos.',
    ],
  },
  {
    locale: 'pt',
    directory: 'i18n/pt/docusaurus-plugin-content-docs-gaming/current',
    titles: ['Notas de Gaming', 'Desenvolvimento de Jogos'],
    emptyStates: [
      'Nenhuma nota de gaming foi publicada ainda.',
      'Nenhum artigo de desenvolvimento de jogos foi publicado ainda.',
    ],
  },
];

// Compile the real MDX, injecting only its two imported Docusaurus dependencies.
// This exercises the landing-page expression, not a duplicate of its logic.
async function renderLanding(content, breadcrumbs) {
  const cardList = vi.fn(() => <div data-testid="entry-cards" />);
  const body = content
    .replace("import DocCardList from '@theme/DocCardList';", '')
    .replace("import { useSidebarBreadcrumbs } from '@docusaurus/plugin-content-docs/client';", '');
  const compiled = await compile(
    `export const { DocCardList, useSidebarBreadcrumbs } = arguments[0];\n\n${body}`,
    { outputFormat: 'function-body' },
  );
  const { default: Landing } = await run(compiled, {
    ...jsxRuntime,
    DocCardList: cardList,
    useSidebarBreadcrumbs: () => breadcrumbs,
  });
  render(<Landing />);
  return cardList;
}

function generateSidebar(section, metadata, frontMatter, children = []) {
  const index = {
    id: `${section}/index`,
    title: frontMatter.title,
    source: `${section}/index.mdx`,
    sourceDirName: section,
    frontMatter,
  };
  const items = DefaultSidebarItemsGenerator({
    docs: [index, ...children],
    item: { type: 'autogenerated', dirName: '.' },
    categoriesMetadata: { [section]: metadata },
    numberPrefixParser: filename => ({ filename }),
    isCategoryIndex: () => false, // The real _category_.json explicitly identifies its index.
  });
  return postProcessSidebars({ gaming: items }, {
    drafts: [],
    sidebarOptions: { sidebarCollapsed: true, sidebarCollapsible: true },
  }).gaming;
}

for (const translations of locales) {
  for (const [index, section] of ['gaming-notes', 'game-development'].entries()) {
    const directory = `${translations.directory}/${section}`;
    const { data: frontMatter, content } = matter(readFileSync(new URL(`${directory}/index.mdx`, root), 'utf8'));
    const metadata = JSON.parse(readFileSync(new URL(`${directory}/_category_.json`, root), 'utf8'));
    const title = translations.titles[index];
    const emptyState = translations.emptyStates[index];

    describe(`${translations.locale}/${section}`, () => {
      it('keeps the translated category reachable when it has no child entries', async () => {
        expect(frontMatter.title).toBe(title);
        expect(frontMatter.sidebar_label).toBe(title);
        expect(frontMatter.description).toBeTruthy();
        expect(metadata.position).toBe(10 + index);
        expect(metadata.label).toContain(title);
        const sidebar = generateSidebar(section, metadata, frontMatter);
        expect(sidebar).toEqual([{ type: 'doc', id: `${section}/index`, label: metadata.label }]);

        // Docusaurus exposes an empty category as a plain link breadcrumb.
        const cardList = await renderLanding(content, [{ type: 'link', docId: sidebar[0].id }]);
        expect(screen.getByRole('heading', { level: 1 })).toHaveTextContent(title);
        expect(screen.getByText(emptyState)).toBeVisible();
        expect(cardList).not.toHaveBeenCalled();
      });

      it('automatically discovers future MDX entries in sidebar order and switches to entry cards', async () => {
        // Test-only metadata: no placeholder posts are published to the site.
        const entries = [999, 998].map(position => ({
          id: `${section}/entry-${position}`,
          title: `Test entry ${position}`,
          source: `${section}/entry-${position}.mdx`,
          sourceDirName: section,
          sidebarPosition: position,
          frontMatter: { sidebar_label: `Test entry ${position}` },
        }));
        const [category] = generateSidebar(section, metadata, frontMatter, entries);
        expect(category.type).toBe('category');
        expect(category.link).toEqual({ type: 'doc', id: `${section}/index` });
        expect(category.items.map(item => item.id)).toEqual([
          `${section}/entry-998`,
          `${section}/entry-999`,
        ]);

        const cardList = await renderLanding(content, [category]);
        expect(screen.queryByText(emptyState)).not.toBeInTheDocument();
        expect(screen.getByTestId('entry-cards')).toBeVisible();
        expect(cardList).toHaveBeenCalled();
      });

      it('falls back safely when sidebar breadcrumbs are unavailable', async () => {
        const cardList = await renderLanding(content, null);
        expect(screen.getByText(emptyState)).toBeVisible();
        expect(cardList).not.toHaveBeenCalled();
      });
    });
  }
}
