name: Build and Deploy Website and Azure Function
on:
  push:
    branches:
      - main
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '/api'
  DOTNET_VERSION: '7.0.x'
jobs:
  build-and-deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Build Docusaurus Website
        run: |
          npm install 
          npm run build
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_MOSS_07D95F50F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/build"
          api_location: "/api"
          output_location: "build"
  build-and-deploy-azure-function:
    runs-on: ubuntu-latest
    needs: build-and-deploy-website
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      - name: 'Deploy Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'dsanchezcr'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C23FC34DC543426B82EF3F665E199E5C }}